---
image: maven:3-openjdk-11

stages:
  - build
  - test
  - quality

variables:
  SAST_JAVA_VERSION: 11

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

compile:
  stage: build
  script:
    - mvn install -DskipTests

testing:
  stage: test
  script:
    - mvn test

sonar:
  stage: quality
  script:
    - mvn -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="${SONAR_CLOUD_LOGIN}"
  allow_failure: true
  only:
    - master
